### ISSUE TITLE
Add option for max simultaneous downloads

### ISSUE THREAD

**Issue by ineffyble** [IonicaBizau/repository-downloader#22]
My laptop is currently unhappy from trying to clone several hundred large repos at once. It would be good if there was a way to specify number of threads/downloads at a time (and maybe some kind of sensible default?)

Happy to provide a patch if you can tell me what your preferred approach is.

**Comment by IonicaBizau** [comment]
Thank you for this issue, @ineffyble!

Currently this is impossible due to this [`parallel`](https://github.com/IonicaBizau/repository-downloader/blob/master/github.js#L200) call.

But it's not complicated to fix it. We can use [`same-time-limit`](https://github.com/IonicaBizau/same-time-limit) to run these functions and later to take the limit from an environment variable or something like that.

Would you like to contribute? :four_leaf_clover:
